# Generated by Django 6.0 on 2025-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_day',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
