# Generated by Django 6.0 on 2025-12-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_slug_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
