# Generated by Django 6.0 on 2025-12-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
